services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: little-soft-chat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: LittleSoftChatDB
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - little-soft-chat-network
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Database Migration Tool
  migration:
    build:
      context: ../../
      dockerfile: src/Tools/LittleSoftChat.Database.Migration/Dockerfile
    container_name: little-soft-chat-migration
    networks:
      - little-soft-chat-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: "no"

volumes:
  mysql_data:
    driver: local

networks:
  little-soft-chat-network:
    external: true
