version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: little-soft-chat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: LittleSoftChatDB
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - little-soft-chat-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:

networks:
  little-soft-chat-network:
    driver: bridge
